### ISSUE TITLE
Last working ROM?

### ISSUE THREAD

**Issue by avivace** [ISSOtm/Aevilia-GB#11]
I know the project has been abandoned, but would it be possible to have at least the "most working" / "last built" ROM? @ISSOtm 

We need it on Homebrew Hub: https://github.com/gbdev/database/tree/master/entries/aevilia

**Comment by FrostedGeulleisia** [comment]
I'll just ask for one thing in case Isso comes here before I get home: some time, because I most likely still have yet to update the actual in-game credits

**Comment by avivace** [comment]
> I'll just ask for one thing in case Isso comes here before I get home: some time, because I most likely still have yet to update the actual in-game credits

Thanks @FrostedGeulleisia !

**Comment by avivace** [comment]
Ping @ISSOtm @FrostedGeulleisia

**Comment by FrostedGeulleisia** [comment]
Sorry  I've been somewhat busy with other stuff and I don't know if Isso even looks at this repo anymore

**Comment by ISSOtm** [comment]
I do, I'm just giving you time to adjust the credits, as you requested.

> I'll just ask for one thing in case Isso comes here before I get home: some time, because I most likely still have yet to update the actual in-game credits

**Comment by FrostedGeulleisia** [comment]
Is the credits system flexible enough that putting in a name of a different length (but still conforming to the character limit) won't break formatting? I don't currently have a way of checking that.

**Comment by ISSOtm** [comment]
Commit the changes you want to see, I'll figure the technical details out, and come back to you privately if need be.
