### ISSUE TITLE
Unknown symbol 'InteriorBlanketCoverTiles'

### ISSUE THREAD

**Issue by SzieberthAdam** [ISSOtm/Aevilia-GB#3]
Windows 7 PC, x64
```
adam@SZAMSI C:\Users\adam\Downloads\Aevilia-GB-master
> compiler.bat
AEVILIA GB version 0.1.0 build 1
=== Compiling... ===

Compile finished.


=== Linking... ===
error: Unknown symbol 'InteriorBlanketCoverTiles'

Darn, build failed. Please fix and try again !
Press any key to continue . . .
```

**Comment by ParzivalWolfram** [comment]
Did you pull the latest files?
EDIT: It seems we broke something. Hang tight, we're on it!

**Comment by ParzivalWolfram** [comment]
Alright, we fixed it! Reclone and rebuild!

**Comment by SzieberthAdam** [comment]
Thanks! I can confirm it fixed.

**Comment by ISSOtm** [comment]
Sorry for that, I have a big change in the works, and syncing the files correctly is a bit difficult.
The game should build, albeit with incomplete data (showing bad sprite graphics).
