### ISSUE TITLE
Saving only works sometimes

### ISSUE THREAD

**Issue by ParzivalWolfram** [ISSOtm/Aevilia-GB#4]
On BGB 1.5.4, saving only works about 1/3 of the time. If I reset manually after saving instead of resetting via the credits, the odds grow to about 1/2. SRAM is updated, so it seems the loader code is causing the issue.

**Comment by ISSOtm** [comment]
I have a 100% save rate on BGB 1.5.5, and (afaik) had also a 100% rate on BGB 1.5.5.

Please detail how "saving doesn't work". (Save corrupted text, before or after intro, or file loading normally but not updated)

**Comment by ParzivalWolfram** [comment]
After saving SRAM is updated but I am still given the "Welcome to a brand new save file!" message after a reset.

**Comment by coderkei** [comment]
I have not had this issue on BGB 1.5.5 and 32k SRAM mode also works fine. Save files from old builds may not be compatible however.

**Comment by ParzivalWolfram** [comment]
the save is generated by the same build that i try to load it on, and it's the build I use for corruptions.
And don't tell me "it's corrupted is why" because the uncorrupt build does it too.

**Comment by ISSOtm** [comment]
You're resetting the game too soon after the game saves, because the flag telling "the file is new" is only cleared at the very end of the saving routine.
Try waiting after the "DONE!" line appears.

**Comment by ISSOtm** [comment]
If you were compiling using the Windows compiler, try the new one (I just updated it). If it persists, then it's weird.

**Comment by ParzivalWolfram** [comment]
This would only be true if I were resetting manually, but it happens even after the credits soft reset the game. And I always wait for that message anyway.

**Comment by ISSOtm** [comment]
Please check if the bug happens consistently (from a single save state, does the bug always occur ?)

**Comment by ParzivalWolfram** [comment]
After recompiling the ROM _and_ redownloading BGB, it saved and reloaded properly 99.8% of the time.
